### ISSUE TITLE
`inverse_transform()` method for unseen data

### ISSUE THREAD

**Issue by slevang** [nicrie/xeofs#101]
I noticed one aspect in which the API deviates from `sklearn`, which is that `inverse_transform()` takes `mode` instead of `X`/`data`. `transform()` does allow passing data. This is a limitation because it means we can only do an inverse transform on the original data, not on new data.

Is there any reason for this, or objection to changing it? My use case would be a model which makes predictions in EOF space, and then you want to inverse transform the output back to gridded space, potentially on new data.

It would be straightforward to implement: we drop [this](https://github.com/nicrie/xeofs/blob/main/xeofs/models/eof.py#L150) and related lines and instead pass through `X` and then select the component modes by whatever is on `X`. It would be a breaking change to the API though, and looks like would also require modifying a lot of tests.

**Comment by nicrie** [comment]
That’s definitely something I’d be keen to change. If I’m not mistaken, there were reasons during the times of version `0.x.y` for the way I implemented things, but I can’t recall the specifics now. Reflecting on it, you appear to be absolutely right.

Even though another breaking change is not ideal, xeofs is still in its early stages and such a change is bound to happen eventually (perhaps better sooner than later?). However, we might keep the `mode` option alongside `X` for backward compatibility. This way, a major release would suffice, and we could phase out support in the future if we're faced with an unavoidable breaking change for a different reason.

Moreover, this approach would spare us a lot of test modifications for the time being. We’d just need a few additional tests for when `X` is provided, but the existing tests could remain unchanged.

**Comment by slevang** [comment]
Maybe a few options then:

1. `inverse_transform(X: DataArray)`, fully breaking change, only allow data, same as sklearn API
2. `inverse_transform(X: DataArray | None = None, mode: int | None = None)`, allow either, assume we have `X` if passed a single positional arg. Breaking change, but would just need to swap the tests to use the kwarg. Compatible with the sklearn API, not identical
3. `inverse_transform(mode: int | None = None, X: DataArray | None = None)`, allow either, non breaking, but still doesn't really match sklearn

**Comment by nicrie** [comment]
tbh I'd be happy with 1, looks the cleanest to me. What would be your preference?

**Comment by slevang** [comment]
Yeah, better to rip the band aid off sooner rather than later. Matching the `sklearn` API seems like a good goal since it is so close everywhere else.

A user can still get the old functionality by doing:
```python
data = model.scores().sel(mode=mode)
model.inverse_transform(data)
```
